"""empty message

Revision ID: 239fa0bbca7d
Revises: 579be61bbad3
Create Date: 2022-06-02 20:58:58.080483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239fa0bbca7d'
down_revision = '579be61bbad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_weather', 'sunrise')
    op.drop_column('daily_weather', 'sunset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_weather', sa.Column('sunset', sa.DATETIME(), nullable=True))
    op.add_column('daily_weather', sa.Column('sunrise', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
