"""empty message

Revision ID: 579be61bbad3
Revises: d1b9f9003579
Create Date: 2022-06-01 21:42:39.822671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579be61bbad3'
down_revision = 'd1b9f9003579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('city', sa.Column('lon', sa.Float(), nullable=False))
    op.create_index(op.f('ix_city_lat'), 'city', ['lat'], unique=False)
    op.create_index(op.f('ix_city_lon'), 'city', ['lon'], unique=False)
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.add_column('daily_weather', sa.Column('precipitation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_weather', 'precipitation')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_index(op.f('ix_city_lon'), table_name='city')
    op.drop_index(op.f('ix_city_lat'), table_name='city')
    op.drop_column('city', 'lon')
    op.drop_column('city', 'lat')
    # ### end Alembic commands ###
