"""tables

Revision ID: d1b9f9003579
Revises: 
Create Date: 2022-05-31 18:54:41.658915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b9f9003579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('daily_weather',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weather_status_id', sa.Integer(), nullable=False),
    sa.Column('day_temp', sa.Float(), nullable=True),
    sa.Column('day_temp_feels', sa.Float(), nullable=True),
    sa.Column('night_temp', sa.Float(), nullable=True),
    sa.Column('night_temp_feels', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['weather_status_id'], ['weather_status.id'], ),
    sa.PrimaryKeyConstraint('city_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_weather')
    op.drop_table('weather_status')
    op.drop_table('city')
    # ### end Alembic commands ###
